// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ethermint/evm/v1/params_v0.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// V0Params defines the EVM module parameters
type V0Params struct {
	// evm_denom represents the token denomination used to run the EVM state
	// transitions.
	EvmDenom string `protobuf:"bytes,1,opt,name=evm_denom,json=evmDenom,proto3" json:"evm_denom,omitempty" yaml:"evm_denom"`
	// enable_create toggles state transitions that use the vm.Create function
	EnableCreate bool `protobuf:"varint,2,opt,name=enable_create,json=enableCreate,proto3" json:"enable_create,omitempty" yaml:"enable_create"`
	// enable_call toggles state transitions that use the vm.Call function
	EnableCall bool `protobuf:"varint,3,opt,name=enable_call,json=enableCall,proto3" json:"enable_call,omitempty" yaml:"enable_call"`
	// extra_eips defines the additional EIPs for the vm.Config
	ExtraEIPs []int64 `protobuf:"varint,4,rep,packed,name=extra_eips,json=extraEips,proto3" json:"extra_eips,omitempty" yaml:"extra_eips"`
	// chain_config defines the EVM chain configuration parameters
	ChainConfig V0ChainConfig `protobuf:"bytes,5,opt,name=chain_config,json=chainConfig,proto3" json:"chain_config"`
	// allow_unprotected_txs defines if replay-protected (i.e non EIP155
	// signed) transactions can be executed on the state machine.
	AllowUnprotectedTxs bool `protobuf:"varint,6,opt,name=allow_unprotected_txs,json=allowUnprotectedTxs,proto3" json:"allow_unprotected_txs,omitempty"`
}

func (m *V0Params) Reset()         { *m = V0Params{} }
func (m *V0Params) String() string { return proto.CompactTextString(m) }
func (*V0Params) ProtoMessage()    {}
func (*V0Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_8430f9b752b9e600, []int{0}
}
func (m *V0Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *V0Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_V0Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *V0Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_V0Params.Merge(m, src)
}
func (m *V0Params) XXX_Size() int {
	return m.Size()
}
func (m *V0Params) XXX_DiscardUnknown() {
	xxx_messageInfo_V0Params.DiscardUnknown(m)
}

var xxx_messageInfo_V0Params proto.InternalMessageInfo

func (m *V0Params) GetEvmDenom() string {
	if m != nil {
		return m.EvmDenom
	}
	return ""
}

func (m *V0Params) GetEnableCreate() bool {
	if m != nil {
		return m.EnableCreate
	}
	return false
}

func (m *V0Params) GetEnableCall() bool {
	if m != nil {
		return m.EnableCall
	}
	return false
}

func (m *V0Params) GetExtraEIPs() []int64 {
	if m != nil {
		return m.ExtraEIPs
	}
	return nil
}

func (m *V0Params) GetChainConfig() V0ChainConfig {
	if m != nil {
		return m.ChainConfig
	}
	return V0ChainConfig{}
}

func (m *V0Params) GetAllowUnprotectedTxs() bool {
	if m != nil {
		return m.AllowUnprotectedTxs
	}
	return false
}

func init() {
	proto.RegisterType((*V0Params)(nil), "ethermint.evm.v1.V0Params")
}

func init() { proto.RegisterFile("ethermint/evm/v1/params_v0.proto", fileDescriptor_8430f9b752b9e600) }

var fileDescriptor_8430f9b752b9e600 = []byte{
	// 400 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0xed, 0xa6, 0x54, 0xf1, 0xa5, 0x48, 0xe5, 0x08, 0xc8, 0xea, 0x60, 0x5b, 0x1e, 0x2a,
	0x4f, 0x76, 0x52, 0x06, 0x24, 0x24, 0x24, 0x70, 0x88, 0x04, 0x5b, 0x65, 0x41, 0x07, 0x16, 0xeb,
	0xe2, 0x3e, 0x1c, 0x4b, 0x77, 0x3e, 0xcb, 0x77, 0x35, 0xee, 0xb7, 0xe0, 0x63, 0x75, 0xec, 0xc8,
	0x64, 0x21, 0xe7, 0x1b, 0x78, 0x60, 0x46, 0xbe, 0x04, 0x27, 0xd0, 0xed, 0xbd, 0xf7, 0xfb, 0xff,
	0xdf, 0xe9, 0xde, 0x1f, 0x39, 0x20, 0xd7, 0x50, 0xb2, 0x2c, 0x97, 0x01, 0x54, 0x2c, 0xa8, 0xe6,
	0x41, 0x41, 0x4a, 0xc2, 0x44, 0x5c, 0xcd, 0xfc, 0xa2, 0xe4, 0x92, 0xe3, 0xb3, 0x41, 0xe1, 0x43,
	0xc5, 0xfc, 0x6a, 0x7e, 0x3e, 0x4d, 0x79, 0xca, 0x15, 0x0c, 0xfa, 0x6a, 0xab, 0x3b, 0xbf, 0x78,
	0xb4, 0x29, 0x59, 0x93, 0x2c, 0x8f, 0x13, 0x9e, 0x7f, 0xcb, 0xd2, 0x61, 0x9f, 0xfb, 0xfb, 0x08,
	0x8d, 0xaf, 0x67, 0x57, 0xea, 0x15, 0x3c, 0x47, 0x06, 0x54, 0x2c, 0xbe, 0x81, 0x9c, 0x33, 0x53,
	0x77, 0x74, 0xcf, 0x08, 0xa7, 0x5d, 0x63, 0x9f, 0xdd, 0x11, 0x46, 0xdf, 0xb8, 0x03, 0x72, 0xa3,
	0x31, 0x54, 0xec, 0x43, 0x5f, 0xe2, 0xb7, 0xe8, 0x29, 0xe4, 0x64, 0x45, 0x21, 0x4e, 0x4a, 0x20,
	0x12, 0xcc, 0x23, 0x47, 0xf7, 0xc6, 0xa1, 0xd9, 0x35, 0xf6, 0x74, 0x67, 0x3b, 0xc4, 0x6e, 0x74,
	0xba, 0xed, 0x17, 0xaa, 0xc5, 0xaf, 0xd1, 0xe4, 0x2f, 0x27, 0x94, 0x9a, 0x23, 0x65, 0x7e, 0xd9,
	0x35, 0x36, 0xfe, 0xd7, 0x4c, 0x28, 0x75, 0x23, 0xb4, 0xb3, 0x12, 0x4a, 0xf1, 0x7b, 0x84, 0xa0,
	0x96, 0x25, 0x89, 0x21, 0x2b, 0x84, 0x79, 0xec, 0x8c, 0xbc, 0x51, 0xe8, 0xb6, 0x8d, 0x6d, 0x2c,
	0xfb, 0xe9, 0xf2, 0xd3, 0x95, 0xe8, 0x1a, 0xfb, 0xd9, 0x6e, 0xc9, 0x20, 0x74, 0x23, 0x43, 0x35,
	0xcb, 0xac, 0x10, 0xf8, 0x23, 0x3a, 0x3d, 0xbc, 0x89, 0xf9, 0xc4, 0xd1, 0xbd, 0xc9, 0xa5, 0xed,
	0xff, 0x7f, 0x61, 0xff, 0x7a, 0xb6, 0xe8, 0x75, 0x0b, 0x25, 0x0b, 0x8f, 0xef, 0x1b, 0x5b, 0x8b,
	0x26, 0xc9, 0x7e, 0x84, 0x2f, 0xd1, 0x0b, 0x42, 0x29, 0xff, 0x1e, 0xdf, 0xe6, 0xfd, 0x55, 0x21,
	0x91, 0x70, 0x13, 0xcb, 0x5a, 0x98, 0x27, 0xfd, 0x7f, 0xa2, 0xe7, 0x0a, 0x7e, 0xd9, 0xb3, 0xcf,
	0xb5, 0x08, 0xdf, 0xdd, 0xb7, 0x96, 0xfe, 0xd0, 0x5a, 0xfa, 0xaf, 0xd6, 0xd2, 0x7f, 0x6c, 0x2c,
	0xed, 0x61, 0x63, 0x69, 0x3f, 0x37, 0x96, 0xf6, 0xf5, 0x22, 0xcd, 0xe4, 0xfa, 0x76, 0xe5, 0x27,
	0x9c, 0xf5, 0xd9, 0x71, 0x11, 0xec, 0xb3, 0xac, 0x55, 0x9a, 0xf2, 0xae, 0x00, 0xb1, 0x3a, 0x51,
	0x09, 0xbe, 0xfa, 0x13, 0x00, 0x00, 0xff, 0xff, 0x26, 0x6c, 0x5e, 0xaa, 0x35, 0x02, 0x00, 0x00,
}

func (m *V0Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *V0Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *V0Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.AllowUnprotectedTxs {
		i--
		if m.AllowUnprotectedTxs {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size, err := m.ChainConfig.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParamsV0(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	if len(m.ExtraEIPs) > 0 {
		dAtA3 := make([]byte, len(m.ExtraEIPs)*10)
		var j2 int
		for _, num1 := range m.ExtraEIPs {
			num := uint64(num1)
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintParamsV0(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x22
	}
	if m.EnableCall {
		i--
		if m.EnableCall {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if m.EnableCreate {
		i--
		if m.EnableCreate {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if len(m.EvmDenom) > 0 {
		i -= len(m.EvmDenom)
		copy(dAtA[i:], m.EvmDenom)
		i = encodeVarintParamsV0(dAtA, i, uint64(len(m.EvmDenom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParamsV0(dAtA []byte, offset int, v uint64) int {
	offset -= sovParamsV0(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *V0Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.EvmDenom)
	if l > 0 {
		n += 1 + l + sovParamsV0(uint64(l))
	}
	if m.EnableCreate {
		n += 2
	}
	if m.EnableCall {
		n += 2
	}
	if len(m.ExtraEIPs) > 0 {
		l = 0
		for _, e := range m.ExtraEIPs {
			l += sovParamsV0(uint64(e))
		}
		n += 1 + sovParamsV0(uint64(l)) + l
	}
	l = m.ChainConfig.Size()
	n += 1 + l + sovParamsV0(uint64(l))
	if m.AllowUnprotectedTxs {
		n += 2
	}
	return n
}

func sovParamsV0(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParamsV0(x uint64) (n int) {
	return sovParamsV0(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *V0Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParamsV0
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: V0Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: V0Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EvmDenom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParamsV0
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParamsV0
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParamsV0
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EvmDenom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableCreate", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParamsV0
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableCreate = bool(v != 0)
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableCall", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParamsV0
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableCall = bool(v != 0)
		case 4:
			if wireType == 0 {
				var v int64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParamsV0
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= int64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ExtraEIPs = append(m.ExtraEIPs, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowParamsV0
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthParamsV0
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthParamsV0
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ExtraEIPs) == 0 {
					m.ExtraEIPs = make([]int64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v int64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowParamsV0
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= int64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ExtraEIPs = append(m.ExtraEIPs, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ExtraEIPs", wireType)
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainConfig", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParamsV0
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParamsV0
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParamsV0
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ChainConfig.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AllowUnprotectedTxs", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParamsV0
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AllowUnprotectedTxs = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipParamsV0(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParamsV0
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParamsV0(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParamsV0
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParamsV0
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParamsV0
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParamsV0
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParamsV0
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParamsV0
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParamsV0        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParamsV0          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParamsV0 = fmt.Errorf("proto: unexpected end of group")
)
